# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python

python:
  - 2.7
  - 3.5

sudo: false

cache:
  apt: true
  pip: true
  directories:
    - $HOME/.cache/pip
    - $HOME/.local

addons:
    packages:
      - gfortran-4.9
      - python-pip

install:
  - |
    if [[ ! -d "$HOME/.local/bin" ]]; then
      mkdir "$HOME/.local/bin"
    fi
  - export PATH="$HOME/.local/bin:$PATH"
  - export FC=/usr/bin/gfortran-4.9
  - ln -fs /usr/bin/gfortran-4.9 "$HOME/.local/bin/gfortran" && gfortran --version
  - ls -l /usr/bin/gfortran-4.9
  - ln -fs /usr/bin/gcov-4.9 "$HOME/.local/bin/gcov" && gcov --version
  - |
    if ! which f90split; then
      wget http://people.sc.fsu.edu/~jburkardt/f_src/f90split/f90split.f90 && \
      gfortran -o f90split f90split.f90 && \
      mv f90split "$HOME/.local/bin/" && \
      rm f90split.f90
    fi
  - pip install --upgrade numpy
  - pip install --upgrade pandas
